#!/bin/sh

run_browser() {
	browser=$1
	version=$2
	description="$browser $version"
	if [ $version = "latest" ]; then
		version=""
	fi

	echo
	echo
	echo "Running $description"
	echo
	USE_SAUCE=true JASMINE_BROWSER=$browser SAUCE_BROWSER_VERSION=$version npm run ci

	if [ $? -eq 0 ]; then
		echo "PASS: $description" >> "$passfile"
	else
		echo "FAIL: $description" >> "$failfile"
	fi
}

passfile=`mktemp -t jasmine-results.XXXXXX` || exit 1
failfile=`mktemp -t jasmine-results.XXXXXX` || exit 1
run_browser chrome latest
run_browser firefox latest
run_browser firefox 91
run_browser safari 15
run_browser safari 14
run_browser MicrosoftEdge latest

echo
cat "$passfile" "$failfile"

if [ -s "$failfile" ]; then
	exit 1
fi
