#!/bin/sh

run_browser() {
	browser=$1
	version=$2
	os="$3"
	description="$browser $version"
	if [ $version = "latest" ]; then
		version=""
	fi

	echo
	echo
	echo "Running $description"
	echo
	USE_SAUCE=true JASMINE_BROWSER=$browser SAUCE_BROWSER_VERSION=$version SAUCE_OS="$os" npm run ci

	if [ $? -eq 0 ]; then
		echo "PASS: $description" >> "$passfile"
	else
		echo "FAIL: $description" >> "$failfile"
	fi
}

passfile=`mktemp -t jasmine-results.XXXXXX` || exit 1
failfile=`mktemp -t jasmine-results.XXXXXX` || exit 1

run_browser chrome latest

run_browser firefox latest
run_browser firefox 128
run_browser firefox 115
run_browser firefox 102
run_browser safari 17
run_browser safari 16
run_browser safari 15
run_browser MicrosoftEdge latest

echo
cat "$passfile" "$failfile"

if [ -s "$failfile" ]; then
	exit 1
fi
